language: python

python:
  - "3.8"

services: docker

script:
  - docker build ./ -t formal_languages --build-arg mod="dif" --build-arg graph="reg.txt" --build-arg regex="ab"
  - docker run formal_languages
  